### ISSUE TITLE
office_text_extractor_1.default is not a function

### ISSUE THREAD

**Issue by queejie** [gamemaker1/office-text-extractor#1]
Hi, and thank you for this utility.  Will I need to install other packages to make this work?  I am getting the default is not a function error on a .docx file.

**Comment by queejie** [comment]
Oh.  Changing from an import to a require did the trick!

**Comment by gamemaker1** [comment]
> Oh. Changing from an import to a require did the trick!

Oh that's great :)

**Comment by mihino89** [comment]
Hello, I have similar question, is it possible to directly import using 'require' library 'office-text-extractor'? I am getting following error after my code: 

```javascript
var extractor = require('office-text-extractor');
```

```bash
internal/modules/cjs/loader.js:1015
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /<path>/node_modules/office-text-extractor/build/index.js
require() of ES modules is not supported.
```

Thank you very much for advice and tool!

**Comment by gamemaker1** [comment]
Hi @mihino89,

The library is an ESM module and thus can't be imported using require. Please see the note about ESM in the `installation` section in the readme.

Regards,
Vedant
