### ISSUE TITLE
Clarity of Browser supports

### ISSUE THREAD

**Issue by lamualfa** [gamemaker1/office-text-extractor#12]
### Description

I don't think this library can run on the browser because the use of `node:buffer` in [`lib.ts`](https://github.com/gamemaker1/office-text-extractor/blob/33445012d2e0da6ab7817540b6dd1d17ce9cdd50/source/lib.ts#L4) file. If so, please remove the Browser section in `readme.md`.

https://github.com/gamemaker1/office-text-extractor/blob/33445012d2e0da6ab7817540b6dd1d17ce9cdd50/readme.md?plain=1#L51

Thanks for the library.

### Library version

3.0.2

### Node version

21

**Comment by gamemaker1** [comment]
Hi,

Sorry for the late reply.

You are right, the package doesn't seem to work in the browser because of the `node:buffer` import. I will remove that section from the readme for now.

Thanks
