### ISSUE TITLE
xlsx newest version is 0.20.1

### ISSUE THREAD

**Issue by chazzmoney** [gamemaker1/office-text-extractor#13]
### Description

Update to xlsx 0.20.1

### Why

0.20.1 changelog:
- init use packaged test files to work around GitHub breaking changes
- SSF date code rounding to 15 decimal digits (h/t [@davidtamaki](https://git.sheetjs.com/davidtamaki))
- sheet_to_json force UTC interpretation for formatted strings (h/t [@Blanay](https://git.sheetjs.com/Blanay))
- QPW extract result of string formula
- XLSX parse non-compliant merge cell expressions
- NUMBERS correctly handle rows omitted from official exports
- DBF parse empty logical field (h/t @Roman91)
- dense option added to types
- package.json add mini and core scripts to export map (h/t [@stof](https://git.sheetjs.com/stof))

### Alternatives

just keep the current version?

**Comment by gamemaker1** [comment]
Thanks, I'll update it right away.
