### ISSUE TITLE
Cant use external url/path

### ISSUE THREAD

**Issue by museadam** [gamemaker1/office-text-extractor#4]
### Description

Any suggestions on how to use an external link?

### Library version

2.0.0

### Node version

19.6.0

### Typescript version (if you are using it)

4.9.5

**Comment by gamemaker1** [comment]
Hi @museadam,

Unfortunately there is no way to read input from an external URL, the package only works with files stored on the physical disk; and doesn't work in the browser either.

Please feel free to make a PR to add this feature :)

Regsrds,
Vedant
