### ISSUE TITLE
Read file from base64 string

### ISSUE THREAD

**Issue by JuanMurciaN** [gamemaker1/office-text-extractor#5]
### Description

Allow the package to use files already loaded to memory, for example in a base64 string, instead of only accepting file paths

### Why

This would allow to process files that during the flow never are saved to disk, but instead are received and ready to be processed

### Alternatives

An alternative is to save the file to then use the package to read it, but then this slows down the process and can overflow disk space for a high number of files if not handled properly

**Comment by gamemaker1** [comment]
Hi there!

Sorry for the late reply :0

This is definitely a feature I want to add to the library, it'll make it much easier to use and add browser support both at once.

I'll take a crack at it sometime this week, or if you want to submit a PR that adds this, that would be epic :D

Regards,
Vedant
